### ISSUE TITLE
the role does not notify all the `sensu` services

### ISSUE THREAD

**Issue by trombik** [reallyenglish/ansible-role-sensu-server#11]
##### ISSUE TYPE

 - Bug Report

##### ROLE VERSION

```
1.1.0
```

##### CONFIGURATION

`tests/integration/example`

##### OS / ENVIRONMENT

FreeBSD

##### SUMMARY

`sensu_server_config_fragments` and `sensu_*_config_fragments`, be it `api`, or `client`, often manage same files to keep common configurations, such as transport. it is also often true that a host runs `sensu-client` and other `sensu` services, such as `sensu-server`, or `sensu-api`.

the following `yaml`:

```yaml
sensu_client_config_fragments:
  rabbitmq:
    rabbitmq:
      host: 192.168.165.201
      port: 5672
      vhost: /sensu
      user: sensu
      password: password
```
creates `/usr/local/etc/sensu/conf.d/rabbitmq.json`, which the two services on the host read.

when the variable changes, the `sensu-client` service will be notified and reloaded. however, the other `sensu` service will not be notified. as a result, the other service keeps old configurations.

this is a common issue among all the `ansible-role-sensu-*` roles.

##### STEPS TO REPRODUCE

run the integration test but do not destroy the test environment. change a value in `sensu_*_config_fragments` and deploy the change.

##### EXPECTED RESULTS

all the `sensu` services are reloaded.

##### ACTUAL RESULTS

not all the `sensu` services are reloaded.
